image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/sphinx-build:1.0.0

build:
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME
    - unzip fonts/ubuntu-font-family-0.83.zip -d /usr/share/fonts/truetype/
    - unzip fonts/source-sans-pro.zip -d /usr/share/fonts/truetype/
    - fc-cache -f
    - git submodule init
    - git submodule update
    - make latexpdf
    - mv build/latex/SakuraTree-Documentation.pdf ./SakuraTree-Documentation.pdf
  tags:
    - docker
  artifacts:
    paths:
      - SakuraTree-Documentation.pdf

